### ISSUE TITLE
存放目录有空格时无法运行

### ISSUE THREAD

**Issue by KB3146706** [1299172402/BBDown_GUI#1]
![image](https://user-images.githubusercontent.com/57534077/153881426-eb8b4605-2d3a-429e-bba7-02df1fb28b34.png)
原始的无此问题
![image](https://user-images.githubusercontent.com/57534077/153883998-b3ed0f12-3786-4e84-b4bd-2ddc7573896d.png)

**Comment by 1299172402** [comment]
fixed
