### ISSUE TITLE
跳过AI字幕功能无法关闭

### ISSUE THREAD

**Issue by Pythame** [1299172402/BBDown_GUI#11]
## **✍问题描述**
在BBDown_GUI中，关闭“跳过AI字幕”功能后仍然会跳过AI字幕下载

## **可能的原因**
在BBDown.exe命令行中，若不做说明则跳过AI字幕是默认开启的，如果要关闭，应在命令中添加“--skip-ai=false”进行说明，而BBDown_GUI并没有添加此项

**Comment by Pythame** [comment]
点错了……

**Comment by 1299172402** [comment]
收到，明天我改改



---Original---
From: ***@***.***&gt;
Sent at: 2023年7月21日(Fri) Evening10:48
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [1299172402/BBDown_GUI] 跳过AI字幕功能无法关闭 (Issue #11)




 
✍问题描述
 
在BBDown_GUI中，关闭“跳过AI字幕”功能后仍然会跳过AI字幕下载
 
可能的原因
 
在BBDown.exe命令行中，若不做说明则跳过AI字幕是默认开启的，如果要关闭，应在命令中添加“--skip-ai=false”进行说明，而BBDown_GUI并没有添加此项

**Comment by 1299172402** [comment]
已修复。可在Actions中获取更新，详见[readme](https://github.com/1299172402/BBDown_GUI#从持续集成中下载beta-version-)
