### ISSUE TITLE
希望更新一下full包里面的BBdown版本

### ISSUE THREAD

**Issue by irx999** [1299172402/BBDown_GUI#24]
没别的希望作者可以full 包里面更新一下bbdown的版本1.60 有一个bug
net_http_message_not_success_statuscode_reason
详见
https://github.com/nilaoda/BBDown/discussions/677

**Comment by 1299172402** [comment]
发布了一个临时的持续构建版本
https://github.com/1299172402/BBDown_GUI/actions/runs/6050171877

从Artifacts中的[BBDown_GUI](https://github.com/1299172402/BBDown_GUI/suites/15729267550/artifacts/898054672)可下载

**Comment by 1299172402** [comment]
也发布了一个 pre-release 版
https://github.com/1299172402/BBDown_GUI/releases/tag/1.1.0-patch
