### ISSUE TITLE
选择的画质判定错误导致下载到错误的画质

### ISSUE THREAD

**Issue by itianmi** [1299172402/BBDown_GUI#28]
## **✍问题描述**
一般来说，选择一个画质，比如“1080P高帧率”，是默认下载的最高画质是这个，如果视频没有这个画质，那么往下低一级画质顺延，比如“1080P高码率”。
有一个bug，我要下载A视频，如果A视频没有“1080P高帧率”画质，实际上它直接跳到A视频的最高画质“4K超清”，这就违背了前面说的常理。
可以看下下载日志，这个应该很容易复现：
[2024-03-22 23:31:51.587] - 加载本地token...
[2024-03-22 23:31:51.720] - 获取aid...
[2024-03-22 23:31:51.720] - 获取aid结束: ep:756173
[2024-03-22 23:31:51.720] - 获取视频信息...
[2024-03-22 23:31:51.860] - 视频标题: 镇魂街 第三季
[2024-03-22 23:31:51.860] - 发布时间: 2023-07-29 20:00:00
[2024-03-22 23:31:51.860] - P1: [1269271114] [1 禁林破晓] [00m00s]
[2024-03-22 23:31:51.860] - P2: [1269271843] [2 草木皆兵] [00m00s]
[2024-03-22 23:31:51.860] - P3: [1269271071] [3 幻楼烽火] [00m00s]
[2024-03-22 23:31:51.860] - P4: [1296933841] [4 兵临城下] [00m00s]
[2024-03-22 23:31:51.860] - P5: [1269270996] [5 水月镜花] [00m00s]
[2024-03-22 23:31:51.860] - ......
[2024-03-22 23:31:51.860] - P16: [1321151527] [16 俯仰千年] [00m00s]
[2024-03-22 23:31:51.860] - 共计 16 个分P, 已选择：ALL
[2024-03-22 23:31:51.860] - 开始解析P1...
[2024-03-22 23:31:52.196] - 共计12条视频流.
0. [4K 超清] [HEVC] [3496 kbps] [~647.90 MB]
1. [1080P 高码率] [HEVC] [1006 kbps] [~186.56 MB]
2. [1080P 高清] [HEVC] [528 kbps] [~97.98 MB]
3. [720P 高清] [HEVC] [297 kbps] [~55.07 MB]
4. [480P 清晰] [HEVC] [177 kbps] [~32.97 MB]
5. [360P 流畅] [HEVC] [113 kbps] [~21.03 MB]
6. [4K 超清] [AVC] [9303 kbps] [~1.68 GB]
7. [1080P 高码率] [AVC] [1607 kbps] [~297.81 MB]
8. [1080P 高清] [AVC] [881 kbps] [~163.25 MB]
9. [720P 高清] [AVC] [526 kbps] [~97.51 MB]
10. [480P 清晰] [AVC] [323 kbps] [~59.91 MB]
11. [360P 流畅] [AVC] [190 kbps] [~35.39 MB]
[2024-03-22 23:31:52.196] - 共计3条音频流.
0. [M4A] [180 kbps] [~34.15 MB]
1. [M4A] [104 kbps] [~19.73 MB]
2. [M4A] [45 kbps] [~8.54 MB]
[2024-03-22 23:31:52.196] - 已选择的流:
[视频] [4K 超清] [HEVC] [3496 kbps] [~647.90 MB]
[音频] [M4A] [180 kbps] [~34.15 MB]
[2024-03-22 23:31:52.196] - 尝试将视频流强制替换为upos-sz-mirrorcoso1.bilivideo.com……
[2024-03-22 23:31:52.196] - 尝试将音频流强制替换为upos-sz-mirrorcoso1.bilivideo.com……
[2024-03-22 23:31:52.197] - 开始多线程下载P1视频...
[#2b1157 0B/647MiB(0%) CN:1 DL:0B]
[#2b1157 31MiB/647MiB(4%) CN:16 DL:31MiB ETA:19s]
[#2b1157 64MiB/647MiB(9%) CN:16 DL:32MiB ETA:17s]
[#2b1157 99MiB/647MiB(15%) CN:16 DL:33MiB ETA:16s]
[#2b1157 133MiB/647MiB(20%) CN:16 DL:33MiB ETA:15s]
[#2b1157 168MiB/647MiB(26%) CN:16 DL:34MiB ETA:14s]
[#2b1157 202MiB/647MiB(31%) CN:16 DL:34MiB ETA:13s]
[#2b1157 236MiB/647MiB(36%) CN:16 DL:34MiB ETA:12s]
[#2b1157 270MiB/647MiB(41%) CN:16 DL:34MiB ETA:11s]
[#2b1157 306MiB/647MiB(47%) CN:16 DL:34MiB ETA:9s]
[#2b1157 340MiB/647MiB(52%) CN:16 DL:34MiB ETA:8s]
[#2b1157 375MiB/647MiB(57%) CN:16 DL:34MiB ETA:7s]
[#2b1157 409MiB/647MiB(63%) CN:16 DL:34MiB ETA:6s]
[#2b1157 443MiB/647MiB(68%) CN:16 DL:34MiB ETA:5s]
[#2b1157 477MiB/647MiB(73%) CN:16 DL:34MiB ETA:4s]
[#2b1157 511MiB/647MiB(79%) CN:16 DL:34MiB ETA:3s]
[#2b1157 545MiB/647MiB(84%) CN:16 DL:34MiB ETA:2s]
[#2b1157 578MiB/647MiB(89%) CN:16 DL:34MiB ETA:2s]
[#2b1157 613MiB/647MiB(94%) CN:12 DL:34MiB ETA:1s]
[#2b1157 643MiB/647MiB(99%) CN:1 DL:34MiB]
[2024-03-22 23:32:14.312] - 合并视频分片...
[2024-03-22 23:32:14.313] - 清理分片...
[2024-03-22 23:32:14.313] - 开始多线程下载P1音频...
[#5a0749 20MiB/33MiB(62%) CN:4 DL:26MiB]
[2024-03-22 23:32:15.948] - 合并音频分片...
[2024-03-22 23:32:15.949] - 清理分片...
[2024-03-22 23:32:15.949] - 下载P1完毕
[2024-03-22 23:32:15.949] - 开始合并音视频...
[2024-03-22 23:32:17.497] - 清理临时文件...

## **📃config.json的内容**
{
    "checkBox_F": true,
    "checkBox_M": true,
    "checkBox_area": false,
    "checkBox_aria2c_args": false,
    "checkBox_aria2c_path": false,
    "checkBox_aria2c_proxy": false,
    "checkBox_audio_only": true,
    "checkBox_c": false,
    "checkBox_danmaku": false,
    "checkBox_debug": false,
    "checkBox_enable_proxy": false,
    "checkBox_ep_host": false,
    "checkBox_ffmpeg": true,
    "checkBox_force_http": true,
    "checkBox_host": false,
    "checkBox_hs": false,
    "checkBox_ia": true,
    "checkBox_info": false,
    "checkBox_language": false,
    "checkBox_mp4box": false,
    "checkBox_mp4box_path": false,
    "checkBox_mt": true,
    "checkBox_p": false,
    "checkBox_p_delay": false,
    "checkBox_p_show_all": false,
    "checkBox_skip_ai": true,
    "checkBox_skip_cover": true,
    "checkBox_skip_mux": false,
    "checkBox_skip_subtitle": true,
    "checkBox_sub_only": false,
    "checkBox_token": false,
    "checkBox_use_aria2c": true,
    "checkBox_video_only": true,
    "comboBox_dfn_more": 5,
    "comboBox_encoding": 3,
    "comboBox_source": 1,
    "lineEdit_F": "<videoTitle>/<videoTitle>-<pageTitle>",
    "lineEdit_M": "<videoTitle>/<videoTitle>-<pageTitle>",
    "lineEdit_area": "",
    "lineEdit_aria2c_args": "",
    "lineEdit_aria2c_path": "C:\\Users\\AAA\\OneDrive\\Tools\\BBDown\\aria2c.exe",
    "lineEdit_aria2c_proxy": "",
    "lineEdit_bbdown": "C:\\Users\\AAA\\OneDrive\\Tools\\BBDown\\BBDown.exe",
    "lineEdit_c": "",
    "lineEdit_dir": "E:\\Downloads",
    "lineEdit_ep_host": "",
    "lineEdit_ffmpeg": "C:\\Users\\AAA\\OneDrive\\Tools\\BBDown\\ffmpeg.exe",
    "lineEdit_host": "",
    "lineEdit_language": "",
    "lineEdit_mp4box_path": "",
    "lineEdit_p": "",
    "lineEdit_p_delay": "",
    "lineEdit_param": "",
    "lineEdit_token": "",
    "lineEdit_url": "https://www.bilibili.com/bangumi/play/ep756173",
    "radioButton_dfn_1080P": false,
    "radioButton_dfn_360P": false,
    "radioButton_dfn_480P": false,
    "radioButton_dfn_720P": false,
    "radioButton_dfn_more": true,
    "radioButton_dfn_priority": false,
    "radioButton_p_all": true,
    "radioButton_p_current": false,
    "radioButton_p_new": false,
    "advanced": true
}

**Comment by 1299172402** [comment]
你向BBDown那边提交一下吧，这是那边的问题
