### ISSUE TITLE
大佬，gui 资源下载不完整，你们有没有遇到这种情况？

### ISSUE THREAD

**Issue by JIKEXIU** [1299172402/BBDown_GUI#3]
![QQ截图20220428175830](https://user-images.githubusercontent.com/53504145/165728496-73c4c7c3-0ec0-493f-a1d2-5dbc1d4efe2e.png)
大佬，gui 资源下载不完整，你们有没有遇到这种情况？

**Comment by 1299172402** [comment]
能具体说下是哪里下载不完整吗

**Comment by JIKEXIU** [comment]
如图，视频跟音频下载百分比进度跟大小不完整。v1.0版本我遇到这种情况，合并后播放还有卡顿，那时候不知道怎么跟你联系，后来就没用过。昨天有个哥们儿给了我v1.0.2版本，我试了下发现还有这种问题，还在测试播放会不会卡顿。这是什么问题，不知道别人有没有这种情况？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1299172402/BBDown_GUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 晚上6:48
***@***.***&gt;;
抄送:&nbsp;"孤影寒梦 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [1299172402/BBDown_GUI] 大佬，gui 资源下载不完整，你们有没有遇到这种情况？ (Issue #3)





 
能具体说下是哪里下载不完整吗

**Comment by 1299172402** [comment]
那应该是 aria2c 输出信息时没有刷新 cmd 输出流缓存的原因，事实上文件应该已经下载完成了。要不然的话，执行到之后的代码也是会报错的

**Comment by 1299172402** [comment]
![image](https://user-images.githubusercontent.com/29673994/165747378-09bb4d9d-1373-4e56-a7b3-5ba0eade153c.png)

这是正常使用 aria2c 时的截图，黄框中即为看到的部分，但实际上可以在下一行看见 Download Complete 的字样。这也说明，虽然在 BBDown和Aria2c的命令行中黄框以外的部分被省略了，但并不代表下载未完成。

**Comment by 1299172402** [comment]
不过视频会卡顿我就不太清楚是什么原因了，你可以重新尝试下载一遍或者尝试用其他版本的ffmpeg或者mp4box混流，如果还是有问题可以找 [BBDown](https://github.com/nilaoda/BBDown) 试着反馈一下，毕竟我也只是做了个界面。。。。

**Comment by JIKEXIU** [comment]
明白了，我也下载了几个视频，这次暂时没发现卡顿现象。另一个问题：国际版，加载 cookie（SESSDATA）清晰度只有480P，什么原因？







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1299172402/BBDown_GUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 晚上8:04
***@***.***&gt;;
抄送:&nbsp;"孤影寒梦 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [1299172402/BBDown_GUI] 大佬，gui 资源下载不完整，你们有没有遇到这种情况？ (Issue #3)





 

 
这是正常使用 aria2c 时的截图，黄框中即为看到的部分，但实际上可以在下一行看见 Download Complete 的字样。这也说明，虽然在 BBDown和Aria2c的命令行中黄框以外的部分被省略了，但并不代表下载未完成。

**Comment by 1299172402** [comment]
这我也不确定了，应该是B站自身原因，我只能说明一些GUI的问题，建议找 [BBDown](https://github.com/nilaoda/BBDown) 反馈
