### ISSUE TITLE
能不能加个批量下载功能？

### ISSUE THREAD

**Issue by carcoonzyk** [1299172402/BBDown_GUI#6]
## **此功能的类型**
- [ ] BBDown 的命令行中存在此功能，而 GUI 中并没有提供

- [x] 关于 GUI 本身的新功能

**Comment by carcoonzyk** [comment]
希望能加个批量下载功能

**Comment by 1299172402** [comment]
能具体说下是想怎么批量下载吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月4日(周四) 凌晨1:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [1299172402/BBDown_GUI] 能不能加个批量下载功能？ (Issue #6)




 
希望能加个批量下载功能

**Comment by 1299172402** [comment]
这个 issue 因为没有回复而关闭。如果后续还是有需要，可以 reopen 这个 issue
