### ISSUE TITLE
从pipy安装的BBDown_GUI在以普通用户运行时无法登录

### ISSUE THREAD

**Issue by mgy-qyqf** [1299172402/BBDown_GUI#7]
## **💭发起问题前**
- [ ] 请确认是界面（此GUI程序）的相关问题
此处无法解决 哔哩哔哩的地区/大会员限制、BBDown自身下载问题、FFmpeg混流问题、Aria2c自身限制 等一类的问题。如您的问题在这些方面，可以到其各自的仓库反馈。

- [ ] 在您反馈问题前，请关闭程序并删除 config.json 重试一次，以保证这不是一次误操作

## **✍问题描述**
从pipy安装的BBDown_GUI在以普通用户登录时无法保存哔哩哔哩登录信息

![图片](https://user-images.githubusercontent.com/73788063/185792222-e6d66f8b-d75b-45d9-b41b-b6fb8ecbd888.png)

这是因为BBDown_GUI将目录默认设置在自己的目录下，而从pip安装会让BBDown_GUI安装在python的site-packages目录下
这个目录是普通用户无法写入文件

解决方案

1. 将`%Python DIR%\Lib\site-packages\BBDown_GUI`改成普通用户可以写入
![图片](https://user-images.githubusercontent.com/73788063/185792605-9ca35c93-a68a-4ebf-9cb9-6c662121df25.png)

2.安装时别用管理员cmd/powershell/root bash让pip把BBDown安装在用户目录下

## **📃config.json的内容**

```json

```

**Comment by 1299172402** [comment]
感谢反馈。这个确实时因为 Python 安装时管理员权限的原因，也谢谢提出解决办法 👍
