### ISSUE TITLE
希望能增加命令导出(显示)功能

### ISSUE THREAD

**Issue by kongbai39** [1299172402/BBDown_GUI#8]
## **此功能的类型**
- [ ] 关于 GUI 本身的新功能

## **功能描述**
希望增加命令导出(显示)功能，方便调整需求

**Comment by 1299172402** [comment]
功能已添加。发布后可以通过下述方式使用

![image](https://user-images.githubusercontent.com/29673994/199964983-712f7338-f754-448d-803f-bce9b8b1d687.png)
