### ISSUE TITLE
大佬好，linux 是否能支持一下？比如某一端口 web 操作

### ISSUE THREAD

**Issue by whistle003** [1299172402/BBDown_GUI#9]
大佬好，能否支持一下 linux 系统？

**Comment by 1299172402** [comment]
linux可以从源码运行，readme里面有写，qt应该是跨平台的。


web的话，暂时没有计划，如果需要的人多再说吧。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月8日(周二) 中午12:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1299172402/BBDown_GUI] 大佬好，linux 是否能支持一下？比如某一端口 web 操作 (Issue #9)




 
大佬好，能否支持一下 linux 系统？
